package com.example.practice.ui.utils

import android.content.Context
import com.example.practice.R

fun Context.localizedAppText(value: String): String = when (value) {
    "Back" -> getString(R.string.back)
    "Next" -> getString(R.string.next)
    "Continue" -> getString(R.string.continue_button)
    "Get Started" -> getString(R.string.get_started)
    "Start" -> getString(R.string.start)
    "Cancel" -> getString(R.string.cancel)
    "Exit" -> getString(R.string.exit)
    "Search" -> getString(R.string.search)
    "Settings" -> getString(R.string.settings)
    "Notification Setting" -> getString(R.string.notification_setting)
    "Notifications Settings" -> getString(R.string.notifications_settings)
    "Password Setting" -> getString(R.string.password_setting)
    "Delete Account" -> getString(R.string.delete_account)
    "General Notification" -> getString(R.string.general_notification)
    "Sound" -> getString(R.string.sound)
    "Vibrate" -> getString(R.string.vibrate)
    "Change Password" -> getString(R.string.change_password)
    "Current Password" -> getString(R.string.current_password)
    "forgot password?", "Forgot Password?" -> getString(R.string.forgot_password)
    "Password" -> getString(R.string.password)
    "New Password" -> getString(R.string.new_password)
    "Confirm New Password" -> getString(R.string.confirm_new_password)
    "Forgotten Password" -> getString(R.string.forgotten_password_title)
    "Enter your email address" -> getString(R.string.enter_email_address)
    "set Password", "Set Password" -> getString(R.string.set_password_title)
    "Reset Password" -> getString(R.string.reset_password)
    "Help & FAQs" -> getString(R.string.help_faqs)
    "How Can We Help You?" -> getString(R.string.help_prompt)
    "Telegram" -> getString(R.string.telegram)
    "Email" -> getString(R.string.email)
    "My Profile" -> getString(R.string.my_profile)
    "Profile" -> getString(R.string.profile)
    "Favorite" -> getString(R.string.favorite)
    "Privacy Policy" -> getString(R.string.privacy_policy)
    "Help" -> getString(R.string.help)
    "Logout" -> getString(R.string.logout)
    "Birthday: April 1st" -> getString(R.string.birthday_april_first)
    "Weight" -> getString(R.string.weight)
    "Years Old" -> getString(R.string.years_old)
    "Height" -> getString(R.string.height)
    "Update Profile" -> getString(R.string.update_profile)
    "You have unsaved changes!" -> getString(R.string.unsaved_changes)
    "Are you sure you want to Delete Account?" -> getString(R.string.delete_account_question)
    "Yes, Del account", "Yes, delete account" -> getString(R.string.yes_delete_account)
    "Are you sure you want to log out?" -> getString(R.string.logout_question)
    "Yes, logout" -> getString(R.string.yes_logout)
    "Favorites" -> getString(R.string.favorites)
    "Sort By" -> getString(R.string.sort_by)
    "All" -> getString(R.string.all)
    "Video" -> getString(R.string.video)
    "Article" -> getString(R.string.article)
    "Hi!" -> getString(R.string.home_hi)
    "It's time to challenge your limits." -> getString(R.string.home_challenge_limits)
    "Recommendations" -> getString(R.string.recommendations)
    "See all" -> getString(R.string.see_all)
    "Articles & Tips" -> getString(R.string.articles_tips)
    "Weekly \nChallenge", "Weekly \n" + "Challenge" -> getString(R.string.weekly_challenge)
    "Cycling\nChallenge" -> getString(R.string.cycling_challenge)
    "Lorem Ipsum Dolor Sit Amet Consectetur.\nMagnis Pellentesque Felis\nUllamcorper Imperdiet." -> getString(R.string.cycling_challenge_description)
    "Plank With Hip Twist" -> getString(R.string.plank_with_hip_twist)
    "Workout" -> getString(R.string.workout)
    "Progress \ntracking", "Progress \n" + "tracking" -> getString(R.string.progress_tracking)
    "Nutrition" -> getString(R.string.nutrition)
    "Community" -> getString(R.string.community)
    "Beginner" -> getString(R.string.beginner)
    "Intermediate" -> getString(R.string.intermediate)
    "Advanced" -> getString(R.string.advanced)
    "Advance" -> getString(R.string.advance)
    "Welcome to" -> getString(R.string.onboarding_welcome_to)
    "Skip" -> getString(R.string.onboarding_skip)
    "Start Your Journey Towards A" -> getString(R.string.onboarding_start_journey_a)
    "More Active Lifestyle" -> getString(R.string.onboarding_more_active_lifestyle)
    "Start Your Journey Towards" -> getString(R.string.onboarding_start_journey)
    "A More Active Lifestyle" -> getString(R.string.onboarding_a_more_active_lifestyle)
    "Find Nutrition Tips That Fit" -> getString(R.string.onboarding_nutrition_title)
    "Your Lifestyle" -> getString(R.string.onboarding_nutrition_description)
    "A Community For You," -> getString(R.string.onboarding_community_title)
    "Challenge Yourself" -> getString(R.string.onboarding_community_description)
    "Consistency Is \nthe Key To progress.\nDon't Give Up!" -> getString(R.string.setup_quote)
    "Stick to your workouts and track your habits. Small daily efforts lead to big results." -> getString(R.string.setup_description)
    "What is Your Gender?" -> getString(R.string.setup_gender_title)
    "This helps us provide personalized recommendations for your workouts and nutrition." -> getString(R.string.setup_gender_description)
    "Male" -> getString(R.string.male)
    "Female" -> getString(R.string.female)
    "How Old Are You?" -> getString(R.string.setup_age_title)
    "Your age helps us tailor workouts and recovery plans that match your body needs." -> getString(R.string.setup_age_description)
    "What Is Your Weight?" -> getString(R.string.setup_weight_title)
    "Knowing your current weight helps us track your progress and set realistic goals." -> getString(R.string.setup_weight_description)
    "What Is Your Height?" -> getString(R.string.setup_height_title)
    "Your height, along with weight, helps calculate your BMI and tailor your fitness plan." -> getString(R.string.setup_height_description)
    "What Is Your Goal?" -> getString(R.string.setup_goal_title)
    "Whether it is building muscle, losing fat, or improving endurance, we will guide you every step." -> getString(R.string.setup_goal_description)
    "Lose Weight" -> getString(R.string.lose_weight)
    "Gain weight" -> getString(R.string.gain_weight)
    "Muscle Mass Gain" -> getString(R.string.muscle_mass_gain)
    "Shape body" -> getString(R.string.shape_body)
    "Others" -> getString(R.string.others)
    "Physical Activity Level" -> getString(R.string.setup_activity_title)
    "Tell us how active you are so we can create a program that fits your lifestyle." -> getString(R.string.setup_activity_description)
    "Fill Your Profile" -> getString(R.string.fill_your_profile)
    "Complete your profile to get the most accurate insights and a personalized fitness plan." -> getString(R.string.fill_profile_description)
    "Full name" -> getString(R.string.full_name)
    "Nickname" -> getString(R.string.nickname)
    "Mobile Number" -> getString(R.string.mobile_number)
    "Years old" -> getString(R.string.years_old_label)
    "Please fill in all required fields" -> getString(R.string.please_fill_required)
    "Choose Date" -> getString(R.string.choose_date)
    "Upper Body" -> getString(R.string.workout_upper_body)
    "Full Body Stretching", "Full Body stretching" -> getString(R.string.workout_full_body_stretching)
    "Glutes & Abs" -> getString(R.string.workout_glutes_abs)
    "Circuit Training" -> getString(R.string.workout_circuit_training)
    "Split Strength Training" -> getString(R.string.workout_split_strength_training)
    "Resistance Training" -> getString(R.string.workout_resistance_training)
    "Upper Body Strength" -> getString(R.string.workout_upper_body_strength)
    "Hypertrophy - Legs", "Hypertrophy – Legs" -> getString(R.string.workout_hypertrophy_legs)
    "Rest or Active Recovery" -> getString(R.string.workout_rest_active_recovery)
    "Pull Out" -> getString(R.string.workout_pull_out)
    "Loop band Exercises" -> getString(R.string.workout_loop_band_exercises)
    "dumbbell step up" -> getString(R.string.workout_dumbbell_step_up)
    "Dumbbell Rows" -> getString(R.string.exercise_dumbbell_rows)
    "Russian Twists" -> getString(R.string.exercise_russian_twists)
    "Squats" -> getString(R.string.exercise_squats)
    "squat Exercise" -> getString(R.string.exercise_squat_exercise)
    "Tabata Intervals" -> getString(R.string.exercise_tabata_intervals)
    "Bicycle Crunches" -> getString(R.string.exercise_bicycle_crunches)
    "Kettlebell Swing" -> getString(R.string.exercise_kettlebell_swing)
    "Shoulder Press" -> getString(R.string.exercise_shoulder_press)
    "Hamstring Curls" -> getString(R.string.exercise_hamstring_curls)
    "Bicep Curls" -> getString(R.string.exercise_bicep_curls)
    "Barbell deadlift" -> getString(R.string.exercise_barbell_deadlift)
    "Barbell Bench Press" -> getString(R.string.exercise_barbell_bench_press)
    "Tricep Dips" -> getString(R.string.exercise_tricep_dips)
    "Incline Bench Sit Up" -> getString(R.string.exercise_incline_bench_sit_up)
    "Romanian Deadlifts" -> getString(R.string.exercise_romanian_deadlifts)
    "Foam Rolling" -> getString(R.string.exercise_foam_rolling)
    "12 Minutes" -> getString(R.string.duration_12_minutes)
    "15 Minutes" -> getString(R.string.duration_15_minutes)
    "20 Minutes" -> getString(R.string.duration_20_minutes)
    "30 Minutes" -> getString(R.string.duration_30_minutes)
    "45 Minutes" -> getString(R.string.duration_45_minutes)
    "50 Minutes" -> getString(R.string.duration_50_minutes)
    "60 Minutes" -> getString(R.string.duration_60_minutes)
    "30 Second" -> getString(R.string.duration_30_second)
    "120 Cal", "120 Kcal" -> getString(R.string.cal_120)
    "150 Cal" -> getString(R.string.cal_150)
    "250 Cal" -> getString(R.string.cal_250)
    "400 Cal" -> getString(R.string.cal_400)
    "785 Kcal" -> getString(R.string.kcal_785)
    "1210 Kcal" -> getString(R.string.kcal_1210)
    "1250 Kcal" -> getString(R.string.kcal_1250)
    "1300 Kcal" -> getString(R.string.kcal_1300)
    "1320 Kcal" -> getString(R.string.kcal_1320)
    "1385 Kcal" -> getString(R.string.kcal_1385)
    "1450 Kcal" -> getString(R.string.kcal_1450)
    "3 Exercises" -> getString(R.string.exercises_3)
    "5 Exercises" -> getString(R.string.exercises_5)
    "10 Exercises" -> getString(R.string.exercises_10)
    "Let's Go Beginner" -> getString(R.string.workout_beginner_title)
    "Explore Different Workout Styles" -> getString(R.string.workout_beginner_subtitle)
    "Keep raising your level" -> getString(R.string.workout_intermediate_title)
    "Explore Intermediate Workouts" -> getString(R.string.workout_intermediate_subtitle)
    "Unlock Your Potential" -> getString(R.string.workout_advanced_title)
    "Explore Advanced Fitness Routines" -> getString(R.string.workout_advanced_subtitle)
    "Intermediate level" -> getString(R.string.intermediate_level)
    "Boost Energy And Vitality" -> getString(R.string.article_boost_energy)
    "Incorporating physical exercise into your daily routine can boost..." -> getString(R.string.article_boost_energy_description)
    "Avocado and egg toast" -> getString(R.string.article_avocado_toast)
    "Lower Body Blast" -> getString(R.string.article_lower_body_blast)
    "A lower body blast is a high-intensity workout focused on targeting..." -> getString(R.string.article_lower_body_description)
    "fruit smoothie" -> getString(R.string.article_fruit_smoothie)
    "Hydrate Properly" -> getString(R.string.article_hydrate_properly)
    "Stay hydrated before, during, and after your workouts to optimize..." -> getString(R.string.article_hydrate_description)
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus libero eget." -> getString(R.string.exercise_description_placeholder)
    "There is no internet connection" -> getString(R.string.no_internet)
    "Email is required" -> getString(R.string.email_required)
    "Password is required" -> getString(R.string.password_required)
    "Full name is required" -> getString(R.string.full_name_required)
    "Nickname is required" -> getString(R.string.nickname_required)
    "Mobile number is required" -> getString(R.string.mobile_number_required)
    "Please confirm your password" -> getString(R.string.confirm_password_required)
    "Passwords do not match" -> getString(R.string.passwords_do_not_match)
    "The passwords do not match", "The passwords don't match", "Пароли не совпадают" -> getString(R.string.passwords_dont_match)
    "Google sign-in is unavailable" -> getString(R.string.google_sign_in_unavailable)
    "Google sign-in failed" -> getString(R.string.google_sign_in_failed)
    "Google ID token not found" -> getString(R.string.google_id_token_not_found)
    "User is null" -> getString(R.string.user_is_null)
    "User not authorized" -> getString(R.string.user_not_authorized)
    "Email not found" -> getString(R.string.email_not_found)
    "Invalid email or password", "Неверная почта или пароль" -> getString(R.string.invalid_email_or_password)
    "Login error", "Ошибка входа" -> getString(R.string.login_error)
    "Enter email", "Введите email" -> getString(R.string.reset_email_required)
    "Email sent. Check your inbox", "Письмо отправлено. Проверьте почту" -> getString(R.string.reset_email_sent)
    "Failed to send email", "Ошибка отправки письма" -> getString(R.string.reset_email_error)
    "Password must be at least 6 characters", "Пароль минимум 6 символов" -> getString(R.string.password_min_6)
    "Password changed successfully", "Пароль успешно изменён" -> getString(R.string.password_changed_success)
    "Password change error", "Ошибка смены пароля" -> getString(R.string.password_change_error)
    "Unknown error" -> getString(R.string.unknown_error)
    "Error", "Ошибка" -> getString(R.string.error)
    "Gender is not selected" -> getString(R.string.gender_not_selected)
    "Goal is not selected" -> getString(R.string.goal_not_selected)
    "Physical activity level is not selected" -> getString(R.string.activity_not_selected)
    "All fields must be filled" -> getString(R.string.all_fields_must_be_filled)
    else -> value
}
